name: 'Bundles'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.3

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: pnpm build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
